name: get_trial.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
    
  push:
    paths:
      - 'trial.cfg'

permissions: write-all

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
         
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare
        run: pip install requests beautifulsoup4 ruamel.yaml json5

      - name: Run get_trial.py
        run: python get_trial.py

      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
        
          git commit -m "Auto update by GitHub Actions"
          git pull --rebase

      - name: Push changes
        if: steps.commit.outcome == 'success'
        run: git push
