name: tg_collector

on:
  workflow_dispatch:
  push:
    paths:
      - 'tg_collector.py'
      - '.github/workflows/tg_collector.yml'
  schedule:
    # 每小时运行一次 (UTC时间，0分时触发)
    - cron: '0 */1 * * *'

jobs:
  run-collector:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install requests tqdm

      - name: Run Collector
        run: python tg_collector.py

      - name: Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          

          git add tg_nodes.txt sub.txt tg_channel_stats.csv

          if git diff --cached --quiet; then
            echo "No changes detected in nodes or stats."
          else
            export TZ='Asia/Shanghai'
            git commit -m "Auto Update: $(date +'%Y-%m-%d %H:%M:%S') (UTC+8)"
            git push
          fi
